---
name: lint
on: push

jobs:
  projects:
    name: projects
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          mapfile -d $'\0' projects < <(find . -maxdepth 1 -mindepth 1 -type d -not -path '*/[.]*' -printf '%P\0')
          echo -n '::set-output name=matrix::{"project": ['
          printf '"%s",' "${projects[@]}" | sed '$s/,$//'
          echo ']}'
  golangci:
    name: lint
    needs: projects
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.projects.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          version: latest
          working-directory: ${{ matrix.project }}
          args: --tests=false

  go:
    name: test
    needs: projects
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.projects.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - run: cd ${{ matrix.project }} && go test ./...
